"use client";

import { toast } from "sonner";
import { useCallback, useState } from "react";

import {
  AlertDrawer,
  AlertDrawerClose,
  AlertDrawerContent,
  AlertDrawerDescription,
  AlertDrawerFooter,
  AlertDrawerHeader,
  AlertDrawerTitle,
  AlertDrawerTrigger,
} from "@altha/core/components/ui/alert-drawer";
import { Button } from "@altha/core/components/ui/button";
import {
  InputOTP,
  InputOTPGroup,
  InputOTPSeparator,
  InputOTPSlot,
} from "@altha/core/components/ui/input-otp";
import { requiresReauthenticate } from "@altha/app/(auth)/_/utils/auth-flow";
import { useReauthenticate } from "@altha/app/(auth)/_/hooks/use-reauthenticate";

import { useActivateTOTP } from "../hooks/use-activate-totp";

export const MfaSetupVerifier = ({
  children,
  onActivated,
}: {
  children: React.ReactNode;
  onActivated: () => void;
}) => {
  const [value, setValue] = useState<string>("");

  const activateTOTP = useActivateTOTP();
  const reauthenticate = useReauthenticate();

  const handleOTP = useCallback(
    (otp: string) => {
      activateTOTP.mutate(
        { code: otp },
        {
          onSettled: () => setValue(""),
          onSuccess: ({ result, success }) => {
            if (!success) {
              const { status } = result;
              if (status === 400) {
                const { errors } = result;
                return errors.forEach((error) => toast.error(error.message));
              }

              if (status === 401) {
                const { data } = result;
                if (requiresReauthenticate(data.flows)) {
                  return handleReauthentication(() => handleOTP(otp));
                }
              }
            }

            return onActivated();
          },
        }
      );
    },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    []
  );

  const handleReauthentication = useCallback((cb: () => void) => {
    const password = prompt("Enter your password to continue:");
    if (password) {
      reauthenticate.mutate(
        { password },
        {
          onSuccess: ({ result, success }) => {
            if (!success) {
              const { status } = result;
              if (status === 400) {
                const { errors } = result;
                return errors.forEach((error) => toast.error(error.message));
              }
            }

            return cb();
          },
        }
      );
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <AlertDrawer>
      <AlertDrawerTrigger asChild>{children}</AlertDrawerTrigger>
      <AlertDrawerContent className="md:max-w-[360px]">
        <AlertDrawerHeader>
          <AlertDrawerTitle className="text-left">
            Verify Your Code
          </AlertDrawerTitle>
          <AlertDrawerDescription>
            Enter the code generated by your app below.
          </AlertDrawerDescription>
        </AlertDrawerHeader>
        <div className="flex flex-col gap-2 p-4 md:p-0">
          <InputOTP
            autoFocus
            maxLength={6}
            onChange={setValue}
            onComplete={handleOTP}
            readOnly={activateTOTP.isPending || reauthenticate.isPending}
            value={value}
          >
            <InputOTPGroup className="flex-1">
              <InputOTPSlot className="flex-1" index={0} />
              <InputOTPSlot className="flex-1" index={1} />
              <InputOTPSlot className="flex-1" index={2} />
            </InputOTPGroup>
            <InputOTPSeparator />
            <InputOTPGroup className="flex-1">
              <InputOTPSlot className="flex-1" index={3} />
              <InputOTPSlot className="flex-1" index={4} />
              <InputOTPSlot className="flex-1" index={5} />
            </InputOTPGroup>
          </InputOTP>
          <p className="text-xs text-center">
            The code refreshes every 30 seconds.
          </p>
        </div>
        <AlertDrawerFooter className="hidden md:flex">
          <AlertDrawerClose asChild className="flex-1">
            <Button
              disabled={activateTOTP.isPending || reauthenticate.isPending}
              loading={activateTOTP.isPending || reauthenticate.isPending}
              variant="outline"
            >
              Close
            </Button>
          </AlertDrawerClose>
        </AlertDrawerFooter>
      </AlertDrawerContent>
    </AlertDrawer>
  );
};
